USE [Project1]
GO

/****** Object:  StoredProcedure [dbo].[FIND_NULLS]    Script Date: 8/1/2024 11:25:39 PM  BY MICHELLE DEBIQUE******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[FIND_NULLS] @TABLENAME VARCHAR(max)
AS

--USE Project1;
DECLARE @MyCursor CURSOR;
DECLARE @FieldName VARCHAR(max);
--DECLARE @TableNAME VARCHAR(max);
DECLARE @SELECTQUERY VARCHAR(max);
DECLARE @SELECTQUERY1 VARCHAR(max);;
DECLARE @TABLEID INT

DECLARE @NULLSTABLE TABLE (FIELD1 VARCHAR(MAX))

--SELECT @TableNAME = '[Project1].[dbo].netflix_titles'-- INPUT TABLE WITH NULLS

SELECT @TABLEID = OBJECT_ID(@TableNAME)  --GET TABLE OBJECT ID

BEGIN
    SET @MyCursor = CURSOR FOR
		SELECT name FROM sys.columns WHERE object_id = @TABLEID

    OPEN @MyCursor 
    FETCH NEXT FROM @MyCursor INTO @FieldName 

    WHILE @@FETCH_STATUS = 0
    BEGIN

		SET @SELECTQUERY1 =('SELECT '''+@FieldName+''' AS NAME, COUNT(*) as NULLS FROM '+@TableNAME+' WHERE [' + @FieldName + '] IS NULL GROUP BY [' +@FieldName +'] UNION ');

		INSERT INTO @NULLSTABLE  VALUES (@SELECTQUERY1) --ALL ROWS ARE NOW AVAILABLE IN FIELD1 COLUMN ON NULLS TABLE

	FETCH NEXT FROM @MyCursor INTO @FieldName 
    END; 

				-- COMBINE ALL RECORDS INTO ONE ROW
				SELECT @SELECTQUERY = 
										LEFT(REPLACE(REPLACE((
											SELECT FIELD1 FROM @NULLSTABLE 
											FOR XML path('')),'<FIELD1>', ''),'</FIELD1>', '')
											, 
											LEN(REPLACE(REPLACE((
											SELECT FIELD1 FROM @NULLSTABLE 
											FOR XML path('')),'<FIELD1>', ''),'</FIELD1>', ''))-5)
											FROM @NULLSTABLE 
		
				EXEC (@SELECTQUERY ) -- AFTER COMBINING RECORDS, EXECUTE LINE

    CLOSE @MyCursor ;
    DEALLOCATE @MyCursor;
END;


--GO;
GO


